name: Feature request
description: Create a report to help us imporve
title: "title"
labels: []
body:
  - type: textarea
    id: overview
    attributes:
     label: 概要
     description: 改善案の概要を書く
  - type: textarea
    id: gole
    attributes:
      label: ゴール・目的
      description: Issueの目的・ゴールを書く
  - type: textarea
    id: design
    attributes:
     label: 仕様・デザイン
     description: 変更があれば書き出す
  - type: textarea
    id: task
    attributes:
      label: タスク
      description: 細かいタスクに分解できているなら書き出す
      placeholder: - [ ]
