name: Bug report
description: Create a report to help us improve
title: ""
labels: []
body:
  - type: textarea
    id: overview
    attributes:
     label: 概要
     description: バグの概要
  - type: textarea
    id: reproduction-procedure
    attributes:
      label: 再現手順
      description: バグの再現手順を箇条書きで書いてください
  - type: textarea
    id: cause
    attributes:
     label: 原因
     description: バグの原因と思われる内容
  - type: textarea
    id: proposed-amendment
    attributes:
     label: 修正案
     description: 現状考えられる修正案があれば書いていく
  - type: textarea
    id: impact
    attributes:
      label: 修正案の影響範囲
      description: 修正案で発生する影響範囲がわかる場合は書いてください
  
