name: Bug Report
description: Create a report to Bug
title: "[Bug]"
labels: ["bug"]
body:
  -type: textarea
    id: description-bug
    attributes:
      value: Describe the bug
      description: 不具合を説明してください

  - type: textarea
    id: reproduction-procedure
    attributes:
      label: 再現手順
      description: バグの再現手順を箇条書きで書いてください
      placeholder: |
        1.TBD
        2.TBD

  -type: textarea
    id: expected-behaviro
    attributes:
      value: Expected behavior
      description: 理想的な動作
      placeholder: |
        1.TBD
        2.TBD

  -type: textarea
    id: expected-behaviro
    attributes:
      value: Environment
      description: 開発環境
      placeholder: |
        Xcode: v15.0
        Swift: 5.10
        iOS: 17.0

