name: Feature request
description: Create a report to help us imporve
title: ""
labels: []
body:
  - type: textarea
    id: overview
    attributes:
     label: 概要
     description: 改善案の概要
  - type: textarea
    id: gole
    attributes:
      label: ゴール・目的
  - type: textarea
    id: design
    attributes:
     label: 使用・デザイン
