name: "Create Airticle"

on:
  workflow_dispatch:
    inputs:
      airticle_name:
        description: "記事のタイトル"
        required: true
        type: string
      branch_name:
        description: "ブランチ名"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Set name and email to Git
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Create and switch work branch
        id: create_work_branch
        run: |
          WORK_BRANCH_NAME="article/${{ github.event.inputs.branch_name }}"
          git switch -c $WORK_BRANCH_NAME
          echo "work_branch_name=$WORK_BRANCH_NAME" >> $GITHUB_ENV
      - name: Create Article
        id: create_article
        run: |
          npm install
          npx qiita new ${{ github.event.inputs.airticle_name }}
          git add .
          git commit -m "Create new Article: ${{ github.event.inputs.airticle_name }}"
          git push origin "article/${{ github.event.inputs.branch_name }}"
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh --version
          gh pr create \
            --title "Create Article #${{ github.event.inputs.airticle_name }}" \
            --body "Pull Request" \
            --base "${{ github.event.repository.default_branch }}" \
            --head "${{ steps.create_work_branch.outputs.work_branch_name }}" \
