name: "Create Airticle"

on:
  workflow_dispatch:
    inputs:
      airticle_name:
        description: '記事のタイトル'
        required: true 
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set name and email to Git
      run: |
        git config --local user.name github-actions[bot]
        git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Create and switch work branch
      id: create_work_branch
      run: |
        WORK_BRANCH_NAME="feature/${{ github.event.inputs.airticle_name }}"
        git switch -c "$WORK_BRANCH_NAME"
        echo "work_branch_name=$WORK_BRANCH_NAME" >> $GITHUB_OUTPUT

    - name: Create post
      id: create_post
      run: |
        npx qiita new ${{ github.event.inputs.airticle_name }}

        git add .
        git commit -m "Create ${{ github.event.inputs.airticle_name }}"
        git push origin ${{ steps.create_work_branch.outputs.work_branch_name }}
        echo "Create Airticle"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create pull request
      run: |
        gh --version
        gh pr create \
          --title "Create ${{ steps.create_post.outputs.post_filename }}" \
          --body "連絡事項があればこちらに記載ください" \
          --base "${{ github.event.repository.default_branch }}" \
          --head "${{ steps.create_work_branch.outputs.work_branch_name }}" \
          --draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}